package ru.govno.client;

import com.google.common.collect.Lists;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Scanner;
import net.minecraft.cape.layer.CustomCapeRenderLayer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.entity.EntityPlayerSP;
import net.minecraft.entity.Entity;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.text.TextComponentTranslation;
import org.lwjgl.Sys;
import ru.govno.client.cfg.ConfigManager;
import ru.govno.client.clickgui.ClickGuiScreen;
import ru.govno.client.clickgui.GuiMusicTuner;
import ru.govno.client.event.EventManager;
import ru.govno.client.friendsystem.FriendManager;
import ru.govno.client.module.ModuleManager;
import ru.govno.client.module.modules.ClientColors;
import ru.govno.client.module.modules.FriendsSLink;
import ru.govno.client.module.modules.PointRender;
import ru.govno.client.utils.ClientRP;
import ru.govno.client.utils.NewYearUtil;
import ru.govno.client.utils.TPSDetect;
import ru.govno.client.utils.UProfilers;
import ru.govno.client.utils.Command.CommandManager;
import ru.govno.client.utils.Command.impl.Panic;
import ru.govno.client.utils.MacroMngr.MacrosManager;
import ru.govno.client.utils.Render.BlurUtil;
import ru.govno.client.utils.Render.ColorUtils;
import ru.govno.client.utils.Render.GlassUtil;
import ru.govno.client.utils.Render.glsandbox.animbackground;
import ru.govno.client.utils.UControllers.DualsenseIntegration;
import viamcp.ViaMCP;

public class Client {
   public static BlurUtil blur;
   public static GlassUtil glass;
   public static String typeUpdate = "Crack";
   public static String releaseType = "TrafimLine";
   public static String updateReason = "by luluv1";
   public static String nameCut = "TrafimLine";
   public static String name = nameCut + " [" + typeUpdate + " " + updateReason + "] PC:" + System.getProperty("user.name");
   public static ArrayList<String> nms = new ArrayList<>();
   public static final String versionCut = "1337";
   public static final String version = "#01337Z";
   public static GuiMusicTuner clickGuiMusic = new GuiMusicTuner("foneticmusic5", 1.0F);
   public static GuiMusicTuner mainGuiNoise = new GuiMusicTuner("main_noise", 3.0F);
   public static PointRender pointRenderer;
   public static ClientColors.ClientColorsHud clientColosUI;
   public static ConfigManager configManager;
   public static ModuleManager moduleManager;
   public static MacrosManager macrosManager;
   public static ClickGuiScreen clickGuiScreen;
   public static FriendManager friendManager;
   public static CommandManager commandManager;
   public static EventManager eventManager;
   public static boolean loadDefault = true;
   public static animbackground screenshader;
   public static long initTime = System.currentTimeMillis();
   public static boolean isFirstStarting = false;
   public static final UProfilers uProfilers = UProfilers.build(850L, "2d objs", "3d objs", "Updates");
   public static boolean badJavaVersion = false;
   public static DualsenseIntegration dualsenseIntegration;
   public static List<ResourceLocation> CONFIG_SAVE_ICONS = new ArrayList<>();
   public static final String clientStrContain = "<<|vlCM|>>";
   public static String staticAddress;

   public static String randomNickname() {
      String[] names = new String[]{
         "VegaLine",
         "RussianPirat",
         "Ladoga",
         "ny7oBKa",
         "IIIuPuHKa",
         "DataBase",
         "KoTuK",
         "nayk",
         "nykaH",
         "nykaJLKa",
         "IIIa7oMeP",
         "Ohtani",
         "Tango",
         "HardStyle",
         "GoToSleep",
         "Movietone",
         "7aIIIuK",
         "TpyCuKu",
         "TheKnight",
         "OnlySprint",
         "Press_W",
         "HowToWASD",
         "BloodFlow",
         "CutVeins",
         "Im_A_Cyber",
         "NextTime",
         "Killer",
         "Murauder",
         "AntiPetuh",
         "CMeTaHKa",
         "Enigma",
         "Doctor",
         "TheGhost",
         "GhostRunner",
         "Banana",
         "Ba3eJLuH",
         "MaCTyp6eK",
         "BaHTy3",
         "AliExpress",
         "Agressor",
         "Spasm",
         "SHAMAN",
         "optimist",
         "",
         "Banker",
         "JahMachine",
         "Cu7aPa",
         "nuBo",
         "CuM6uoT",
         "Venom",
         "Superman",
         "Supreme",
         "CeKcU_6ou",
         "SuperSpeed",
         "KnuckKnuck",
         "6o7aTbIPb",
         "SouthPark",
         "Simpson",
         "IIIaJLaIII",
         "3_Penetrate",
         "EmptySoul",
         "Firefly",
         "PlusTopka",
         "TryMe",
         "YouAreWeak",
         "MegaSexual",
         "Pikachu",
         "Pupsik",
         "Legenda",
         "SCP",
         "MyNumber",
         "YourToy",
         "SexShop",
         "Slayer",
         "Murderer",
         "CallMe",
         "PvpTeacher",
         "CrazyVega",
         "4ynuK",
         "6aToH",
         "LongPenis",
         "Caxap",
         "Infernal",
         "Vegota",
         "Vegator",
         "Vegoza",
         "Veglin",
         "Devo4ka",
         "SexySister",
         "NakedBody",
         "PlusZ4",
         "ThiefInLaw",
         "StrongTea",
         "BlackTea",
         "SmallAss",
         "SmallBoobs",
         "CoffeeDEV",
         "FireRider",
         "MilkyWay",
         "PeacefulBoy",
         "Lambada",
         "MagicSpeed",
         "ThrowMom",
         "StopPlay",
         "KillMother",
         "XDeadForGay",
         "ALTf4",
         "HowAreYou",
         "GoSex",
         "Falas",
         "Sediment",
         "OpenDoor",
         "ShitInTrap",
         "SuckItUp",
         "NeuroNET",
         "BunnyHop",
         "BmxSport",
         "GiveCoord",
         "eHoTuK",
         "KucKa",
         "3auKa",
         "4aIIIa",
         "HykaHax",
         "Sweet",
         "MoHuTop",
         "Me7aMa4o",
         "Miner",
         "BonAqua",
         "COK",
         "BANK",
         "Lucky",
         "SPECTATE",
         "7OBHO",
         "MyXA",
         "Owner",
         "5opka",
         "JUK",
         "FaceBreak",
         "SnapBody",
         "Psycho",
         "EasyWin",
         "SoHard",
         "Panties",
         "SoloGame",
         "Robot",
         "Surgeon",
         "_IMBA",
         "ShakeMe",
         "EnterMe",
         "GoAway",
         "TRUE",
         "while",
         "Pinky",
         "Pickup",
         "Stack",
         "GL11",
         "GLSL",
         "Garbage",
         "NoBanMe",
         "WiFi",
         "Tally",
         "Dream",
         "Mommy",
         "6aTya",
         "Pivovar",
         "Alkash",
         "Gangsta",
         "Counter",
         "Clitor",
         "HentaUser",
         "BrowseHent",
         "LoadChunk",
         "Panical",
         "Kakashka",
         "MinusVse",
         "Pavlik",
         "RusskiPirat",
         "GoodTrip",
         "6A6KA",
         "3000IQ",
         "0IQ",
         "VEGA33",
         "YOUR_BOSS",
         "CPacketGay",
         "4Bytes",
         "SinCos",
         "Yogurt",
         "SexInTrash",
         "TrashMyHome",
         "PenisUser",
         "VaginaLine",
         "VagLine",
         "Virginia",
         "NoReportMe",
         "Bluetouth",
         "PivoBak",
         "6AKJLAXA",
         "Opostrof",
         "Harming",
         "Cauldron",
         "Dripka",
         "Wurdulak",
         "Presedent",
         "Opstol",
         "Oposum",
         "Babayka",
         "O4KAPUK",
         "Dunozavr",
         "Cocacola",
         "Fantazy",
         "70JLA9I",
         "PedalKTLeave",
         "TolstoLobik",
         "nePDyH",
         "HABO3HUK",
         "KOT",
         "CKOT",
         "BISHOP",
         "4ukeH",
         "nanaxa",
         "Berkyt",
         "Matreshka",
         "HACBAU",
         "XAPEK",
         "Mopedik",
         "CKELET2013",
         "GodDrakona",
         "CoLHbiIIIKo",
         "HA77ETC",
         "PoM6uK",
         "PomaH",
         "6oM6UJLa",
         "MOH7OJl",
         "OutOfMemory",
         "PopkaDurak",
         "4nokVPupok",
         "Pinality",
         "Shaverma",
         "MOJLUCb",
         "MOJLuTBA",
         "CTEHA",
         "CKAJLA",
         "JohnWeak",
         "Plomba",
         "neKaPb",
         "Disconnect",
         "Oriflame",
         "Mojang",
         "TPPPPP",
         "EvilBoy",
         "DavaiEbaca",
         "TuMeuT",
         "Tapan",
         "600K7Puzo",
         "Poctelecom",
         "Interzet",
         "C_6oDUHA",
         "6yHTaPb",
         "Milka",
         "KOLBASA",
         "OhNo",
         "YesTea",
         "Mistik",
         "KuHDep",
         "Smippy",
         "Diamond",
         "KedpOBuK",
         "Lolikill",
         "CrazyGirl",
         "Kronos",
         "Kruasan",
         "MrProper",
         "HellCat",
         "Nameless",
         "Viper",
         "GamerYT",
         "slimer",
         "MrSlender",
         "Gromila",
         "BoomBoom",
         "Doshik",
         "BananaKenT",
         "NeonPlay",
         "Progibator",
         "Rubak",
         "MrMurzik",
         "Kenda",
         "DrShine",
         "cnacu6o",
         "Eclips",
         "ShadowFuse",
         "DrVega",
         "Bacardi",
         "UwU_FUF",
         "Exont",
         "Persik",
         "Mambl",
         "Rossamaha",
         "DrKraken",
         "MeWormy",
         "WaterBomb",
         "YourStarix",
         "nakeTuk",
         "Massik",
         "MineFOX",
         "BitCoin",
         "Avocado",
         "Chappi",
         "ECEQO",
         "Fondy",
         "StableFace",
         "JeBobby",
         "KrytoyKaka",
         "MagHyCEp",
         "I7evice",
         "LeSoulles",
         "EmptySoul",
         "KOMnOT",
         "MrPlay",
         "NGROK2009",
         "NoProblem",
         "MrPatric",
         "OkugAmas",
         "YaBuilder",
         "A7EHT007",
         "PussyGirl",
         "Triavan",
         "TyCoBKa",
         "UnsafeINV",
         "yKcyc_UFO",
         "Wendy",
         "Bendy",
         "XAOC",
         "ST6yP7",
         "XYNECI",
         "HENTAI",
         "YoutDaddy",
         "YouGurT",
         "EnumFacing",
         "HitVec3d",
         "JavaGypy",
         "VIWEBY",
         "ZamyPlay",
         "SUSUKI",
         "KPAX_TRAX",
         "Emiron",
         "UzeXilo",
         "Rembal",
         "Gejmer",
         "EvoNeon",
         "MrFazen",
         "ESHKERE",
         "FARADENZA",
         "EarWarm",
         "CMA3KA",
         "NaVi4oK",
         "A4_OMG",
         "YCYSAPO",
         "Booster",
         "BroDaga",
         "CastlePlay29",
         "DYWAHY",
         "Emirhan",
         "BezPontov",
         "Xilece",
         "Gigabait",
         "Griefer",
         "Goliaf",
         "Fallaut",
         "HERODOT",
         "KingKong",
         "NADOBNO",
         "ODIZIT",
         "Klawdy",
         "NCRurtler",
         "Fixik",
         "FINISHIST",
         "KPACOTA",
         "GlintEff",
         "Flexer",
         "NeverMore",
         "BludShaper",
         "PoSaN4Ik",
         "Goblin",
         "Aligator",
         "Zmeyka",
         "FieFoxe",
         "Homilion",
         "Locator",
         "kranpus",
         "HOLSON",
         "CocyD_ADA",
         "Anarant",
         "O6pUKoc",
         "MissTitan",
         "JellyKOT",
         "JellyCat",
         "LolGgYT",
         "MapTiNi",
         "GazVax",
         "Foxx4ever",
         "NaGiBaToP",
         "whiteKing",
         "KitKat",
         "VkEdAx",
         "Pro100Hy6",
         "Contex",
         "Durex",
         "Mr_Golem",
         "Moonlight",
         "CoolBoy",
         "6oTaH",
         "CaHa6uC",
         "MuJLaIIIKa",
         "AvtoBus",
         "ABOBA",
         "KanaTuK",
         "TpanoFob",
         "CAPSLOCK",
         "Sonic",
         "SONIK",
         "COHUK",
         "Tailss",
         "TAILSS",
         "TauJLC",
         "Ehidna",
         "exudHa",
         "Naklz",
         "HaKJL3",
         "coHuk",
         "parebuh",
         "nape6yx",
         "TEPOPNCT",
         "TPEHEP",
         "6OKCEP",
         "KARATE_TYAN",
         "Astolfo",
         "Itsuki",
         "Yotsuba",
         "Succub",
         "CyKKy6",
         "MuJLaIIIKa",
         "Chappie",
         "LeraPala4",
         "MegaSonic",
         "ME7A_COHUK",
         "SonicEzh",
         "IIaPe6yx",
         "Flamingo",
         "Pavlin",
         "VenusShop",
         "PinkRabbit",
         "EpicSonic",
         "EpicTailss",
         "Genius",
         "Valkiria",
         "Leviafan",
         "Levitate",
         "Praha",
         "Google",
         "EveryFar",
         "noToMoK",
         "Joy",
         "NotFitKill",
         "Gang",
         "Bomjara",
         "Vodka",
         "Harry",
         "Lurker",
         "Butterfly",
         "sweetheart",
         "Paradise",
         "Fidelity",
         "Guitar",
         "TheGod",
         "MA7A",
         "BUFF",
         "Fermer",
         "Jolly",
         "Apart",
         "Rift",
         "VoidWalker",
         "Feral",
         "BLOWUP",
         "cupid",
         "Arthur",
         "Vovan",
         "PS6",
         "SwordKiss",
         "MnogoFPS",
         "SuperPower",
         "Overcharge",
         "IPoh20Pro",
         "XXFine",
         "ThickLegs",
         "vegaOS",
         "XAngel",
         "BloodHand",
         "EvilRage",
         "IIIunoBKa",
         "TapaH",
         "K76",
         "Hawk",
         "Pride",
         "Sapphire",
         "sexoil",
         "SexOil",
         "Vaseline",
         "Haha_Women",
         "Taher",
         "Sumoist",
         "BONG",
         "Koc9iK",
         "BitterCum",
         "TheDevil",
         "BoSin",
         "Chip",
         "Avatar",
         "TomCruise",
         "AngryPotato",
         "YouSlut",
         "Spiral",
         "7paHaTa",
         "7a4uXa4",
         "6peBHo",
         "YanagiBurp",
         "MadBoy",
         "MadMan",
         "HateMe",
         "Anonimus",
         "PianoRap",
         "HVPmaster",
         "GinLamp",
         "Potions",
         "naHda",
         "MoonMood",
         "sportsman",
         "YourFatMom",
         "YourLardMom",
         "CTPAX",
         "YourFear",
         "Rivet",
         "Geforce",
         "LeavePedal",
         "FCKu",
         "SeeOnMe",
         "SeaChill",
         "Negrator",
         "Niggatron",
         "EvilGranny",
         "Wand",
         "PlusTopka",
         "TheHero",
         "krokodildo",
         "TakeShit",
         "KissMyAss",
         "TakeMyEggs",
         "BigEggs",
         "CHAunEp",
         "Tekken",
         "WizKhalifa",
         "Shadow",
         "KuJLaK",
         "7aHTeJL9i",
         "PlusO4KO",
         "suppressor",
         "Duellist",
         "McPoh",
         "AnusGuard",
         "Treniti",
         "30FOV",
         "Vegalab",
         "Grenka",
         "TORNADO",
         "Agent",
         "Hammer",
         "IPickYou",
         "4e6yP",
         "Мo9i_Samka",
         "Enot1k",
         "NiceTry",
         "BlazeCat",
         "Chaos",
         "SOOOOOS",
         "LooserSOSO",
         "FaloMet",
         "obosralipsis",
         "Rat",
         "RougeTheBat",
         "RedLaser",
         "Xenomorph",
         "xxtennation",
         "FistingEye",
         "20HP",
         "DoSquirt",
         "IamComming",
         "Heronwater",
         "npopok",
         "silence",
         "Unity",
         "Impulse",
         "pulse3d",
         "GIANT",
         "Zombie",
         "Leviton",
         "Jura",
         "Bird",
         "Dinazaur",
         "CpaHb",
         "GoToHax",
         "CuCbKu",
         "nuCbKa",
         "3aCpaHeu",
         "pidRoblox",
         "Pioneer",
         "Flappy",
         "TiDurak",
         "zxcLoh",
         "MatkaBreaker",
         "Tamagotchi",
         "Klakson",
         "Kolokol",
         "YeatCASH",
         "PartyBurn",
         "Frontiers",
         "BoomEarth",
         "FallenStar",
         "Sackboy",
         "cuddly",
         "CARNAGE",
         "Jester",
         "Spark",
         "LoveShard",
         "HeartShard",
         "FemKiller",
         "Suckvibe",
         "Bibika",
         "Slider",
         "FaceControl",
         "FaceID",
         "6o4Ka",
         "PACTPAXOH",
         "DrXyu",
         "RenderRave",
         "KaIIIaJLoT",
         "Pubertat",
         "ny6epTaT",
         "KupKa",
         "CJLe3a",
         "RUBILA",
         "ImElite",
         "grill",
         "bmxSalto",
         "PureEnergy",
         "Twix",
         "cocucka",
         "kalash",
         "PikaPi",
         "WARDEN",
         "evilSlime",
         "Godzilla",
         "DaiDeneg",
         "Atmos",
         "Abema",
         "MeowSuck",
         "Sigmatron",
         "FartJeans",
         "FartToChair",
         "SockSmell",
         "DickSmell",
         "EggsSmell",
         "SmellFear",
         "3anaxJLo",
         "ouuYea",
         "cowbell",
         "Cy4ka",
         "Eu_Cy4Ka",
         "BOMJ",
         "Petards",
         "SkyFox",
         "POMNI",
         "Pomni",
         "Jex",
         "Circus",
         "ChocoPie",
         "DOLBY",
         "AntiPaste",
         "Insomniac",
         "Windows",
         "Shaman",
         "Bird",
         "Water",
         "Egor",
         "Zaika",
         "Petrushka",
         "Lalka",
         "Kotik",
         "Furrie6",
         "Nigrator",
         "Neggro",
         "Sfotkal",
         "TABLO",
         "4eIIIKa",
         "Lapka",
         "3acpaHeu",
         "zadnica",
         "dualanus",
         "4yna4ync",
         "RocketLeague",
         "Jessi",
         "Hissenberg",
         "RTX6090",
         "PopkaPuk",
         "DrugLab",
         "CuH9IK",
         "nyncuk",
         "npuBeT",
         "3uCy4ka",
         "KSAS1000W",
         "Dinnerbomj",
         "Furry",
         "Yiff",
         "XA4",
         "PSPlus",
         "Selena",
         "selena",
         "Saros",
         "HoneyBunny",
         "SugarCube",
         "LovelyLily",
         "PinkPanda",
         "CuddlyKitty",
         "CuddlyVL",
         "Jasmine",
         "Pixie",
         "Muffin",
         "Treasure",
         "Unicorn",
         "Zephyr",
         "Starlet",
         "Hedgehog",
         "Owl",
         "Silk",
         "Squirrel",
         "Extrasex",
         "Penguin",
         "Knuckles",
         "Amy",
         "Saros"
      };
      String[] titles = new String[]{
         "DADA",
         "YA",
         "2001",
         "2002",
         "2003",
         "2004",
         "2005",
         "2006",
         "2007",
         "2008",
         "2009",
         "2010",
         "2011",
         "2012",
         "2013",
         "2014",
         "2015",
         "2016",
         "2000",
         "2025",
         "2077",
         "777",
         "092",
         "SUS",
         "SSS",
         "TAM",
         "TyT",
         "TaM",
         "Ok",
         "Pon",
         "LoL",
         "CHO",
         "4oo",
         "MaM",
         "Top",
         "PvP",
         "PVH",
         "DIK",
         "KAK",
         "SUN",
         "SIN",
         "COS",
         "FIT",
         "FAT",
         "HA",
         "AHH",
         "OHH",
         "UwU",
         "DA",
         "NaN",
         "RAP",
         "WoW",
         "SHO",
         "KA4",
         "Ka4",
         "AgA",
         "Fov",
         "LoVe",
         "TAN",
         "Mia",
         "Alt",
         "4el",
         "bot",
         "GlO",
         "Sir",
         "IO",
         "EX",
         "Mac",
         "Win",
         "Lin",
         "AC",
         "Bro",
         "6po",
         "6PO",
         "BRO",
         "mXn",
         "XiL",
         "TGN",
         "24",
         "228",
         "1337",
         "1488",
         "007",
         "001",
         "999",
         "333",
         "666",
         "111",
         "FBI",
         "FBR",
         "FuN",
         "FUN",
         "UFO",
         "OLD",
         "Old",
         "New",
         "OFF",
         "ON",
         "YES",
         "LIS",
         "NEO",
         "BAN",
         "OwO",
         "0_o",
         "0_0",
         "o_0",
         "IQ",
         "99K",
         "AK47",
         "SOS",
         "S0S",
         "SoS",
         "z0z",
         "zOz",
         "Zzz",
         "zzz",
         "ZZZ",
         "6y",
         "BU",
         "RAK",
         "PAK",
         "Pak",
         "MeM",
         "MoM",
         "M0M",
         "KAK",
         "TAK",
         "n0H",
         "BOSS",
         "RU",
         "ENG",
         "BAF",
         "BAD",
         "ZED",
         "oy",
         "Oy",
         "0y",
         "Big",
         "Air",
         "Dirt",
         "Dog",
         "CaT",
         "CAT",
         "KOT",
         "EYE",
         "CAN",
         "ToY",
         "ONE",
         "OIL",
         "HOT",
         "HoT",
         "VPN",
         "BnH",
         "Ty3",
         "GUN",
         "HZ",
         "XZ",
         "XYZ",
         "HZ",
         "XyZ",
         "HIS",
         "HER",
         "DOC",
         "COM",
         "DIS",
         "TOP",
         "1ST",
         "1st",
         "LORD",
         "DED",
         "ded",
         "HAK",
         "FUF",
         "IQQ",
         "KBH",
         "KVN",
         "HuH",
         "WWW",
         "RUN",
         "RuN",
         "run",
         "PRO",
         "100",
         "300",
         "3OO",
         "RAM",
         "DIR",
         "Yaw",
         "YAW",
         "TIP",
         "Tun",
         "Ton",
         "Tom",
         "Your",
         "AM",
         "FM",
         "YT",
         "yt",
         "Yt",
         "yT",
         "RUS",
         "KON",
         "FAK",
         "FUL",
         "RIL",
         "pul",
         "RW",
         "MST",
         "MEN",
         "MAN",
         "NO0",
         "SEX",
         "H2O",
         "H20",
         "LyT",
         "3000",
         "01",
         "KEK",
         "PUK",
         "nuk",
         "nyk",
         "nyK",
         "191",
         "192",
         "32O",
         "5OO",
         "320",
         "500",
         "777",
         "720",
         "480",
         "48O",
         "HUK",
         "BUS",
         "LUN",
         "LyH",
         "Fuu",
         "LaN",
         "LAN",
         "DIC",
         "HAA",
         "NON",
         "FAP",
         "4AK",
         "4on",
         "4EK",
         "4eK",
         "NVM",
         "BOG",
         "RIP",
         "SON",
         "XXL",
         "XXX",
         "GIT",
         "GAD",
         "8GB",
         "5G",
         "4G",
         "3G",
         "2G",
         "TX",
         "GTX",
         "RTX",
         "HOP",
         "TIR",
         "ufo",
         "MIR",
         "MAG",
         "ALI",
         "BOB",
         "GRO",
         "GOT",
         "ME",
         "SO",
         "Ay4",
         "MSK",
         "MCK",
         "RAY",
         "EVA",
         "EvA",
         "DEL",
         "ADD",
         "UP",
         "VK",
         "LOV",
         "AND",
         "AVG",
         "EGO",
         "YTY",
         "YoY",
         "I_I",
         "G_G",
         "D_D",
         "V_V",
         "F",
         "FF",
         "FFF",
         "LCM",
         "PCM",
         "CPS",
         "FPS",
         "GO",
         "G0",
         "70",
         "7UP",
         "JAZ",
         "GAZ",
         "7A3",
         "UFA",
         "HIT",
         "DAY",
         "DaY",
         "S00",
         "SCP",
         "FUK",
         "SIL",
         "COK",
         "SOK",
         "WAT",
         "WHO",
         "PUP",
         "PuP",
         "Py",
         "CPy",
         "SRU",
         "OII",
         "IO",
         "IS",
         "THE",
         "SHE",
         "nuc",
         "KXN",
         "VAL",
         "MIS",
         "HXI",
         "HI",
         "ByE",
         "WEB",
         "TNT",
         "BEE",
         "4CB",
         "III",
         "IVI",
         "POP",
         "C4",
         "BRUH",
         "Myp",
         "MyP",
         "NET",
         "CAR",
         "PET",
         "POV",
         "POG",
         "OKK",
         "ESP",
         "GOP",
         "G0P",
         "7on",
         "E6y",
         "BIT",
         "PIX",
         "AYE",
         "Aye",
         "PVP",
         "GAS",
         "REK",
         "rek",
         "PEK",
         "n0H",
         "RGB",
         "job",
         "sea",
         "up",
         "hah",
         "dmn",
         "foo",
         "fsb",
         "cps",
         "fck",
         "sru",
         "cpy",
         "ona",
         "fan",
         "xex",
         "SO",
         "p1p",
         "0",
         "ZERO",
         "op",
         "YO",
         "yo",
         "LL",
         "QYS",
         "POP",
         "NA",
         "volt",
         "CUP",
         "hop",
         "pip",
         "sip",
         "SUB"
      };
      String name = names[(int)(((float)names.length - 1.0F) * (float)Math.random() * (((float)names.length - 1.0F) / (float)names.length))];
      int attempts = 60;
      boolean chanceStart = Math.random() > 0.85;

      for (int i = 0; i < attempts; i++) {
         String title = titles[(int)(((float)titles.length - 1.0F) * (float)Math.random() * (((float)titles.length - 1.0F) / (float)titles.length))];
         String finalName = chanceStart ? title + "_" + name : name + "_" + title;
         int size = finalName.length();
         if (size <= 16) {
            return finalName;
         }
      }

      return chanceStart ? "__" + name : "_" + name + "_";
   }

   public static void run() {
      Minecraft.stage("check sys properties");
      ClientRP.getInstance().init();
      Minecraft.stage("load discord instance");
      ClientRP.getInstance().getDiscordRP().start();
      Minecraft.stage("start rich presence");

      try {
         CustomCapeRenderLayer.capeFrames = new ResourceLocation[60];

         for (int i = 0; i < 59; i++) {
            CustomCapeRenderLayer.capeFrames[i] = new ResourceLocation("vegaline/capes/animated/animation4/c" + (i + 1) + ".png");
         }

         Minecraft.stage("init client-cape tickable frames");

         for (int i = 0; i < 59; i++) {
            Minecraft.getMinecraft().getTextureManager().bindTexture(CustomCapeRenderLayer.capeFrames[i]);
            Minecraft.stage("load client-cape tickable frame №" + i);
         }
      } catch (Exception var7) {
         var7.fillInStackTrace();
      }

      try {
         int framesCount = 62;
         String path = "vegaline/ui/minecraft/config/animation0/";
         String baseName = "safecfgframe";
         String format = ".jpg";

         for (int num = 0; num <= 62; num++) {
            ResourceLocation frame = new ResourceLocation("vegaline/ui/minecraft/config/animation0/safecfgframe" + num + ".jpg");
            CONFIG_SAVE_ICONS.add(frame);
         }

         Minecraft.stage("init config-save tickable frames");

         for (int num = 0; num <= 62; num++) {
            Minecraft.getMinecraft().getTextureManager().bindTexture(CONFIG_SAVE_ICONS.get(num));
            Minecraft.stage("load config-save tickable frame №" + num);
         }
      } catch (Exception var6) {
         var6.fillInStackTrace();
      }

      new TPSDetect();
      Minecraft.stage("init tps detect");
      clientColosUI = new ClientColors.ClientColorsHud();
      Minecraft.stage("init ui color manager");
      blur = new BlurUtil();
      Minecraft.stage("init blur tool");
      glass = new GlassUtil();
      Minecraft.stage("itil glass tool");
      configManager = new ConfigManager();
      Minecraft.stage("init confog manager");
      commandManager = new CommandManager();
      Minecraft.stage("init command manager");
      moduleManager = new ModuleManager();
      Minecraft.stage("init modules");
      pointRenderer = new PointRender();
      Minecraft.stage("init points");
      macrosManager = new MacrosManager();
      Minecraft.stage("init macroses");
      eventManager = new EventManager();
      Minecraft.stage("init C-events");
      clickGuiScreen = new ClickGuiScreen();
      Minecraft.stage("init client gui");
      friendManager = new FriendManager();
      Minecraft.stage("init friends manager");
      if (new File(ConfigManager.configDirectory, "nulled.vls") == null
         || new File(ConfigManager.configDirectory, "nulled.vls").length() < 1000L
         || configManager.findConfig("nulled") == null) {
         isFirstStarting = true;
         FriendsSLink.SHOW_GUIDE_ON_FIRST_START = true;
      }

      Minecraft.stage("check first starting" + (isFirstStarting ? " +" : ""));
      configManager.saveConfig("nulled");
      Minecraft.stage("swap defaults");
      if (configManager.findConfig("Default") != null) {
         configManager.loadConfig("Default");
      }

      Minecraft.stage("load starting cfg");
      dualsenseIntegration = new DualsenseIntegration();
      Minecraft.stage("load dualsense integration");
      NewYearUtil.init();
      Minecraft.stage("load new year integration");
   }

   public static void initVia() {
      try {
         ViaMCP.create();
      } catch (Exception var1) {
         var1.fillInStackTrace();
      }
   }

   public static void msg(String s, boolean prefix) {
      s = "<<|vlCM|>>" + (prefix ? "§bVegaLine > " : "") + "§7" + s;

      try {
         if (Minecraft.player != null && Minecraft.player.ticksExisted >= 1) {
            Minecraft.player.addChatMessage(new TextComponentTranslation(s.replace("&", "??")));
         }
      } catch (Exception var3) {
         var3.fillInStackTrace();
      }
   }

   public static void msg(int s, boolean prefix) {
      String a = "<<|vlCM|>>" + (prefix ? "§bVegaLine > " : "") + "§7" + s;
      if (Minecraft.player != null && Minecraft.player.ticksExisted >= 1) {
         Minecraft.player.addChatMessage(new TextComponentTranslation(a.replace("&", "??")));
      }
   }

   public static void msg(boolean s, boolean prefix) {
      String a = "<<|vlCM|>>" + (prefix ? "§bVegaLine > " : "") + "§7" + s;
      if (Minecraft.player != null && Minecraft.player.ticksExisted >= 1) {
         Minecraft.player.addChatMessage(new TextComponentTranslation(a.replace("&", "??")));
      }
   }

   public static void msg(double s, boolean prefix) {
      String a = "<<|vlCM|>>" + (prefix ? "§bVegaLine > " : "") + "§7" + s;
      if (Minecraft.player != null && Minecraft.player.ticksExisted >= 1) {
         Minecraft.player.addChatMessage(new TextComponentTranslation(a.replace("&", "??")));
      }
   }

   public static void msg(float s, boolean prefix) {
      String a = "<<|vlCM|>>" + (prefix ? "§bVegaLine > " : "") + "§7" + s;
      if (Minecraft.player != null && Minecraft.player.ticksExisted >= 1) {
         Minecraft.player.addChatMessage(new TextComponentTranslation(a.replace("&", "??")));
      }
   }

   public static boolean summit(Entity f) {
      return false;
   }

   public static void qw(String stat) {
   }

   public static ArrayList<Client.ServerListPresetElement> getPresetsServersList() {
         return new ArrayList<>();
   }

   public static class ServerListPresetElement {
      private final String serverName;
      private final String serverIp;
      private final String serverDescription;
      private final int serverColor;

      public ServerListPresetElement(String serverName, String serverIp, String serverDescription, int serverColor) {
         this.serverName = serverName;
         this.serverIp = serverIp;
         this.serverDescription = serverDescription;
         this.serverColor = serverColor;
      }

      public String getServerName() {
         return this.serverName;
      }

      public String getServerIp() {
         return this.serverIp;
      }

      public String getServerDescription() {
         return this.serverDescription;
      }

      public int getServerColor() {
         return this.serverColor;
      }
   }
}
