package ru.govno.client.module;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import net.minecraft.client.Minecraft;
import ru.govno.client.module.modules.AimAssist;
import ru.govno.client.module.modules.AirJump;
import ru.govno.client.module.modules.AirStuck;
import ru.govno.client.module.modules.AntiBot;
import ru.govno.client.module.modules.AntiCrystal;
import ru.govno.client.module.modules.AutoApple;
import ru.govno.client.module.modules.AutoCrystal;
import ru.govno.client.module.modules.AutoLeave;
import ru.govno.client.module.modules.AutoPlay;
import ru.govno.client.module.modules.AutoWebTrap;
import ru.govno.client.module.modules.BackTrack;
import ru.govno.client.module.modules.BadTrip;
import ru.govno.client.module.modules.BedwarsHelper;
import ru.govno.client.module.modules.BowAimbot;
import ru.govno.client.module.modules.BowSpam;
import ru.govno.client.module.modules.Bypass;
import ru.govno.client.module.modules.CaveFinder;
import ru.govno.client.module.modules.Charming;
import ru.govno.client.module.modules.ChatHelper;
import ru.govno.client.module.modules.ChestChecker;
import ru.govno.client.module.modules.ChestStealer;
import ru.govno.client.module.modules.ChinaHat;
import ru.govno.client.module.modules.ClickGui;
import ru.govno.client.module.modules.ClickTeleport;
import ru.govno.client.module.modules.ClientColors;
import ru.govno.client.module.modules.ClientTune;
import ru.govno.client.module.modules.ComfortUi;
import ru.govno.client.module.modules.CommandGui;
import ru.govno.client.module.modules.Criticals;
import ru.govno.client.module.modules.Crosshair;
import ru.govno.client.module.modules.CrystalBooster;
import ru.govno.client.module.modules.DashCubics;
import ru.govno.client.module.modules.DashTrail;
import ru.govno.client.module.modules.DeathBox;
import ru.govno.client.module.modules.Derping;
import ru.govno.client.module.modules.DistantAlpha;
import ru.govno.client.module.modules.DualsenseSupport;
import ru.govno.client.module.modules.ESP;
import ru.govno.client.module.modules.ElytraBoost;
import ru.govno.client.module.modules.EntityBox;
import ru.govno.client.module.modules.FakePlayer;
import ru.govno.client.module.modules.FireFlies;
import ru.govno.client.module.modules.Fly;
import ru.govno.client.module.modules.FragEffects;
import ru.govno.client.module.modules.FreeCam;
import ru.govno.client.module.modules.FriendsSLink;
import ru.govno.client.module.modules.GameSyncTPS;
import ru.govno.client.module.modules.HighJump;
import ru.govno.client.module.modules.HitAura;
import ru.govno.client.module.modules.HitBubble;
import ru.govno.client.module.modules.HoleESP;
import ru.govno.client.module.modules.Hud;
import ru.govno.client.module.modules.InvMngr;
import ru.govno.client.module.modules.InvWalk;
import ru.govno.client.module.modules.JesusSpeed;
import ru.govno.client.module.modules.JumpCircles;
import ru.govno.client.module.modules.LineGlyphs;
import ru.govno.client.module.modules.LongJump;
import ru.govno.client.module.modules.MiddleClick;
import ru.govno.client.module.modules.MiniMap;
import ru.govno.client.module.modules.MoveHelper;
import ru.govno.client.module.modules.NameSecurity;
import ru.govno.client.module.modules.NameTags;
import ru.govno.client.module.modules.NoClip;
import ru.govno.client.module.modules.NoInteract;
import ru.govno.client.module.modules.NoRender;
import ru.govno.client.module.modules.Notifications;
import ru.govno.client.module.modules.Nuker;
import ru.govno.client.module.modules.OffHand;
import ru.govno.client.module.modules.OnFalling;
import ru.govno.client.module.modules.Particles;
import ru.govno.client.module.modules.PearlFlight;
import ru.govno.client.module.modules.Penis;
import ru.govno.client.module.modules.PenisBuilder;
import ru.govno.client.module.modules.Phase;
import ru.govno.client.module.modules.PickBlowup;
import ru.govno.client.module.modules.PlayerHelper;
import ru.govno.client.module.modules.PotionBrewer;
import ru.govno.client.module.modules.PotionThrower;
import ru.govno.client.module.modules.ProContainer;
import ru.govno.client.module.modules.PushAttack;
import ru.govno.client.module.modules.RadioPlayer;
import ru.govno.client.module.modules.Respawn;
import ru.govno.client.module.modules.STabMonitor;
import ru.govno.client.module.modules.ScaffWalk;
import ru.govno.client.module.modules.SchoolBoy;
import ru.govno.client.module.modules.SexAura;
import ru.govno.client.module.modules.Speed;
import ru.govno.client.module.modules.Spider;
import ru.govno.client.module.modules.StormHVHHelper;
import ru.govno.client.module.modules.Strafe;
import ru.govno.client.module.modules.Surround;
import ru.govno.client.module.modules.TPExploit;
import ru.govno.client.module.modules.TPInfluence;
import ru.govno.client.module.modules.TargetHUD;
import ru.govno.client.module.modules.TargetStrafe;
import ru.govno.client.module.modules.ThrowDirs;
import ru.govno.client.module.modules.ThrowFollow;
import ru.govno.client.module.modules.ThrowPetard;
import ru.govno.client.module.modules.Timer;
import ru.govno.client.module.modules.TopkaSort;
import ru.govno.client.module.modules.TotemPopESP;
import ru.govno.client.module.modules.TpDirections;
import ru.govno.client.module.modules.Tracers;
import ru.govno.client.module.modules.Triangular;
import ru.govno.client.module.modules.UiScaleControl;
import ru.govno.client.module.modules.VClip;
import ru.govno.client.module.modules.Velocity;
import ru.govno.client.module.modules.ViewModel;
import ru.govno.client.module.modules.WallHack;
import ru.govno.client.module.modules.WaterSpeed;
import ru.govno.client.module.modules.WorldChat;
import ru.govno.client.module.modules.WorldRender;
import ru.govno.client.module.modules.Xray;
import ru.govno.client.newfont.Fonts;
import ru.govno.client.utils.CrystalField;

public class ModuleManager {
   public List<Module> modules = new ArrayList<>();
   public static ModuleManager.safe safed;
   public List<String> moduleDescription = new ArrayList<>();

   public ModuleManager() {
      this.modules.add(new UiScaleControl());
      Minecraft.stage("ui scale control module");
      this.modules.add(new ClientColors());
      Minecraft.stage("client colors module");
      this.modules.add(new SexAura());
      Minecraft.stage(" module");
      this.modules.add(new PickBlowup());
      Minecraft.stage("pick blowup module");
      this.modules.add(new FireFlies());
      Minecraft.stage("fire flies module");
      this.modules.add(new HitBubble());
      Minecraft.stage("hit bubbles module");
      this.modules.add(new STabMonitor());
      Minecraft.stage("init s tab monitor");
      this.modules.add(new WallHack());
      Minecraft.stage("wall hack module");
      this.modules.add(new ScaffWalk());
      Minecraft.stage("scaff walk module");
      this.modules.add(new HitAura());
      Minecraft.stage("hit aura module");
      this.modules.add(new CommandGui());
      Minecraft.stage("command gui module");
      this.modules.add(new StormHVHHelper());
      Minecraft.stage("storm hvh helper module");
      this.modules.add(new PotionThrower());
      Minecraft.stage("potion thrower module");
      this.modules.add(new Charming());
      Minecraft.stage("charming module");
      this.modules.add(new Triangular());
      Minecraft.stage("triangular module");
      this.modules.add(new ESP());
      Minecraft.stage("esp module");
      this.modules.add(new DeathBox());
      Minecraft.stage("death box module");
      this.modules.add(new AutoLeave());
      Minecraft.stage("auto leave module");
      this.modules.add(new JumpCircles());
      Minecraft.stage("jump circles module");
      this.modules.add(new CrystalField());
      Minecraft.stage("crystal field module");
      this.modules.add(new WorldRender());
      Minecraft.stage("world render module");
      this.modules.add(new PlayerHelper());
      Minecraft.stage("player helper module");
      this.modules.add(new MoveHelper());
      Minecraft.stage("move helper module");
      this.modules.add(new TotemPopESP());
      Minecraft.stage("totem pop ESP module");
      this.modules.add(new HoleESP());
      Minecraft.stage("hole ESP module");
      this.modules.add(new GameSyncTPS());
      Minecraft.stage("game sync tps module");
      this.modules.add(new Nuker());
      Minecraft.stage("nuker module");
      this.modules.add(new LineGlyphs());
      Minecraft.stage("line glyphs module");
      this.modules.add(new SchoolBoy());
      Minecraft.stage("school boy module");
      this.modules.add(new AutoWebTrap());
      Minecraft.stage("web trap module");
      this.modules.add(new AimAssist());
      Minecraft.stage("aim assist module");
      this.modules.add(new Hud());
      Minecraft.stage("hud module");
      this.modules.add(new ClickGui());
      Minecraft.stage("click gui module");
      this.modules.add(new Surround());
      Minecraft.stage("surround module");
      this.modules.add(new ComfortUi());
      Minecraft.stage("comfort ui module");
      this.modules.add(new PotionBrewer());
      Minecraft.stage("potion brewer module");
      this.modules.add(new Phase());
      Minecraft.stage("phase module");
      this.modules.add(new TPExploit());
      Minecraft.stage("tp exploit module");
      this.modules.add(new ChestStealer());
      Minecraft.stage("chest stealer module");
      this.modules.add(new Velocity());
      Minecraft.stage("velocity module");
      this.modules.add(new Speed());
      Minecraft.stage("speed module");
      this.modules.add(new WaterSpeed());
      Minecraft.stage("water speed module");
      this.modules.add(new PushAttack());
      Minecraft.stage("push attack module");
      this.modules.add(new JesusSpeed());
      Minecraft.stage("jesus speed module");
      this.modules.add(new NoClip());
      Minecraft.stage("no clip module");
      this.modules.add(new FreeCam());
      Minecraft.stage("free cam module");
      this.modules.add(new AirJump());
      Minecraft.stage("air jump module");
      this.modules.add(new HighJump());
      Minecraft.stage("high jump module");
      this.modules.add(new AntiCrystal());
      Minecraft.stage("anti crystal module");
      this.modules.add(new PearlFlight());
      Minecraft.stage("pearl flight module");
      this.modules.add(new BowSpam());
      Minecraft.stage("bow spam module");
      this.modules.add(new EntityBox());
      Minecraft.stage("entity box module");
      this.modules.add(new Particles());
      Minecraft.stage("particles module");
      this.modules.add(new AutoCrystal());
      Minecraft.stage("auto crystal module");
      this.modules.add(new TargetHUD());
      Minecraft.stage("target hud module");
      this.modules.add(new Notifications());
      Minecraft.stage("notifications module");
      this.modules.add(new NameSecurity());
      Minecraft.stage("name security module");
      this.modules.add(new Xray());
      Minecraft.stage("xray module");
      this.modules.add(new ClientTune());
      Minecraft.stage("client tune module");
      this.modules.add(new ChatHelper());
      Minecraft.stage("chat helper module");
      this.modules.add(new NoInteract());
      Minecraft.stage("no interact module");
      this.modules.add(new ClickTeleport());
      Minecraft.stage("click teleport module");
      this.modules.add(new AntiBot());
      Minecraft.stage("anti bot module");
      this.modules.add(new TopkaSort());
      Minecraft.stage("topka sort module");
      this.modules.add(new VClip());
      Minecraft.stage("vclip module");
      this.modules.add(new LongJump());
      Minecraft.stage("long jump module");
      this.modules.add(new ElytraBoost());
      Minecraft.stage("elytra boost module");
      this.modules.add(new Respawn());
      Minecraft.stage("respawn module");
      this.modules.add(new BowAimbot());
      Minecraft.stage("bow aimbot module");
      this.modules.add(new OffHand());
      Minecraft.stage("off hand module");
      this.modules.add(new Criticals());
      Minecraft.stage("criticals module");
      this.modules.add(new Bypass());
      Minecraft.stage("bypass module");
      this.modules.add(new AutoApple());
      Minecraft.stage("auto apple module");
      this.modules.add(new ProContainer());
      Minecraft.stage("pro container module");
      this.modules.add(new OnFalling());
      Minecraft.stage("on falling module");
      this.modules.add(new TargetStrafe());
      Minecraft.stage("target strafe module");
      this.modules.add(new ViewModel());
      Minecraft.stage("view model module");
      this.modules.add(new InvMngr());
      Minecraft.stage("inv mngr module");
      this.modules.add(new NoRender());
      Minecraft.stage("no render module");
      this.modules.add(new Crosshair());
      Minecraft.stage("crosshair module");
      this.modules.add(new Fly());
      Minecraft.stage("fly module");
      this.modules.add(new FakePlayer());
      Minecraft.stage("fake player module");
      this.modules.add(new Spider());
      Minecraft.stage("spider module");
      this.modules.add(new InvWalk());
      Minecraft.stage("inv walk module");
      this.modules.add(new Timer());
      Minecraft.stage("timer module");
      this.modules.add(new NameTags());
      Minecraft.stage("nametags module");
      this.modules.add(new Tracers());
      Minecraft.stage("tracers module");
      this.modules.add(new Strafe());
      Minecraft.stage("strafe module");
      this.modules.add(new MiddleClick());
      Minecraft.stage("middle click module");
      this.modules.add(new DashTrail());
      Minecraft.stage("dash trail module");
      this.modules.add(new DashCubics());
      Minecraft.stage("dash cubics module");
      this.modules.add(new TpDirections());
      Minecraft.stage("tp directions module");
      this.modules.add(new ThrowDirs());
      Minecraft.stage("throw dirs module");
      this.modules.add(new TPInfluence());
      Minecraft.stage("tp influence module");
      this.modules.add(new CaveFinder());
      Minecraft.stage("cave finder module");
      this.modules.add(new FragEffects());
      Minecraft.stage("frag effects module");
      this.modules.add(new CrystalBooster());
      Minecraft.stage("crystal booster module");
      this.modules.add(new MiniMap());
      Minecraft.stage("minimap module");
      this.modules.add(new ThrowPetard());
      Minecraft.stage("throw petard module");
      this.modules.add(new ThrowFollow());
      Minecraft.stage("throw follow module");
      this.modules.add(new BadTrip());
      Minecraft.stage("bad trip module");
      this.modules.add(new PenisBuilder());
      Minecraft.stage("penis builder module");
      this.modules.add(new DistantAlpha());
      Minecraft.stage("distant alpha module");
      this.modules.add(new BackTrack());
      Minecraft.stage("back track module");
      this.modules.add(new AutoPlay());
      Minecraft.stage("auto play module");
      this.modules.add(new ChinaHat());
      Minecraft.stage("china hat module");
      this.modules.add(new FriendsSLink());
      Minecraft.stage("friends s link module");
      this.modules.add(new Obosralipsis());
      Minecraft.stage("obosralipsis module");
      this.modules.add(new Derping());
      Minecraft.stage("derping module");
      this.modules.add(new WorldChat());
      Minecraft.stage("world chat module");
      this.modules.add(new RadioPlayer());
      Minecraft.stage("radio player module");
      this.modules.add(new BedwarsHelper());
      Minecraft.stage("bed wars helper module");
      this.modules.add(new AirStuck());
      Minecraft.stage("air stuck module");
      this.modules.add(new ChestChecker());
      Minecraft.stage("chest checker module");
      this.modules.add(new DualsenseSupport());
      Minecraft.stage("penis module");
      this.modules.add(new Penis());
      Minecraft.stage("dualsense support module");
      this.moduleDescription
         .add(
            "UiScaleControlУправляет настройками масштаба отображения UI и доступности, может вызвать сбои работы VL и высокие значения ForceMinecraftScale могут быть недоступны на некоторых разрешениях экрана"
         );
      this.moduleDescription.add("SexAuraПялит в жопу игроков");
      this.moduleDescription.add("FireFliesВокруг вас будут летать светлячки");
      this.moduleDescription.add("HitBubbleКрасивые эффекты от удара");
      this.moduleDescription.add("PickBlowupРисует кружки под предметами которые были подобраны вами");
      this.moduleDescription.add("WallHackВидно существ через стены");
      this.moduleDescription.add("ScaffWalkСтроит мост блоками");
      this.moduleDescription.add("HitAuraСамостоятельно убивает всё живое в радиусе действия");
      this.moduleDescription.add("CommandGuiУдобное использование комманд мышкой");
      this.moduleDescription.add("StormHVHHelperПомогает играть на шторм хвх");
      this.moduleDescription.add("PotionThrowerСамостоятельно кидает полезные зелья");
      this.moduleDescription.add("CharmingЛетающий приятель");
      this.moduleDescription.add("TriangularПоказывает стрелки ведущие к существам");
      this.moduleDescription.add("ESPАналогия Wallhack.");
      this.moduleDescription.add("DeathBoxОставляет информативный бокс с тегом при смерти существ.");
      this.moduleDescription.add("AutoLeaveИзбегает контакта с игроками.");
      this.moduleDescription.add("JumpCirclesРисует круги от прышка");
      this.moduleDescription.add("CrystalFieldКристальный пвп бот, умеет самостоятельно ставить обсидиан");
      this.moduleDescription.add("WorldRenderУкрашает игру");
      this.moduleDescription.add("PlayerHelperПрофессионал в помощи поставке/ломании блоков и подобное");
      this.moduleDescription.add("MoveHelperВспомогательный инструмент для движений");
      this.moduleDescription.add("TotemPopESPСпавнит приведение при использовании тотема любым игроком");
      this.moduleDescription.add("HoleESPПодсвечивает ''холки'' куда можно прыгнуть");
      this.moduleDescription.add("GameSyncTPSСинхронизирует игру с сервером");
      this.moduleDescription.add("NukerЛомает блоки вокруг вас");
      this.moduleDescription.add("LineGlyphsРисует метричные линии в мире");
      this.moduleDescription.add("SchoolBoyУменьшает существ до роста ''детей''");
      this.moduleDescription.add("AutoWebTrapСтавит паутину в существ/игроков");
      this.moduleDescription.add("AimAssistПомогает прицеливаться в пвп");
      this.moduleDescription.add("HudДобавляет оверлей клиента");
      this.moduleDescription.add("ClickGuiМеню этого чита");
      this.moduleDescription.add("SurroundСтавит вокруг вас обсидиан");
      this.moduleDescription.add("ComfortUiВсячески улучшает воприятие и взаимодействия в разных Ui");
      this.moduleDescription.add("PotionBrewerПивовар");
      this.moduleDescription.add("PhaseДаёт пройти в стену");
      this.moduleDescription.add("TPExploitТелепортирует на старую точку");
      this.moduleDescription.add("ChestStealerЛутает сундуки");
      this.moduleDescription.add("VelocityБлокирует откидывание");
      this.moduleDescription.add("SpeedУскоряет передвижение");
      this.moduleDescription.add("WaterSpeedУскоряет в воде");
      this.moduleDescription.add("PushAttackПозволяет бить и использовать предметы");
      this.moduleDescription.add("JesusSpeedПозволяет бегать/летать по воде");
      this.moduleDescription.add("NoClipХодьба/телепорт сквозь блоки");
      this.moduleDescription.add("FreeCamКамера обзора местности");
      this.moduleDescription.add("AirJumpПрыжки от воздухa");
      this.moduleDescription.add("HighJumpУвеличивает высоту прыжка");
      this.moduleDescription.add("AntiCrystalБлокирует обсидиан/бедрок блоками");
      this.moduleDescription.add("PearlFlightПолёт от урона эндер жемчуга");
      this.moduleDescription.add("ScaffoldСтроит мост блоками");
      this.moduleDescription.add("BowSpamБыстро стреляет луком");
      this.moduleDescription.add("EntityBoxИзменяет боксы существ и может сделать ваши руки 'длиннее'");
      this.moduleDescription.add("ParticlesЛетающие частицы от урона");
      this.moduleDescription.add("AutoCrystalСам ставит/взрывает кристалл на поставленный обсидиан");
      this.moduleDescription.add("TargetHUDРисует табличку с информацией о текущем таргете");
      this.moduleDescription.add("NotificationsПоказывает уведомления");
      this.moduleDescription.add("NameSecurityСкрывает ваш никнейм");
      this.moduleDescription.add("XrayИщет руды через стены");
      this.moduleDescription.add("ClientTuneВоспроизводит звуки клиента");
      this.moduleDescription.add("ChatHelperВспомогательный бот для чата");
      this.moduleDescription.add("NoInteractБлокирует клик по умным блокам");
      this.moduleDescription.add("ClickTeleportТелепортирует при пкм по взгляду");
      this.moduleDescription.add("AntiBotУдаляет ботов из мира");
      this.moduleDescription.add("TopkaSortСортирует кучу ресурсов под вами");
      this.moduleDescription.add("VClipВертикальный телепорт");
      this.moduleDescription.add("LongJumpПолёт/ускорение от урона");
      this.moduleDescription.add("ElytraBoostПолёт/ускорение с элитрами");
      this.moduleDescription.add("RespawnАвтоматически возраждает вас");
      this.moduleDescription.add("BowAimbotАвтоматичетки наводится на существ луком учитывая траекторию полёта стрелы");
      this.moduleDescription.add("OffHandУмно использует тотемы и прочие предметы левой рукой");
      this.moduleDescription.add("CriticalsПри возможности наносит увеличенный урон");
      this.moduleDescription.add("BypassОслабляет воздействие античита");
      this.moduleDescription.add("AutoAppleАвтоматически хилится золотыми яблоками");
      this.moduleDescription.add("ChinaHatРисует крутую шляпу");
      this.moduleDescription.add("ProContainerУпрощает работу с инвентарём");
      this.moduleDescription.add("OnFallingДейсвует при падении с высоты");
      this.moduleDescription.add("TargetStrafeБегает вокруг противника Aura");
      this.moduleDescription.add("ViewModelМеняет позицию рук");
      this.moduleDescription.add("InvMngrСортирует/чистит инвентарь");
      this.moduleDescription.add("NoRenderУбирает мешающие элементы игры");
      this.moduleDescription.add("CrosshairМеняет вид прицела на экране");
      this.moduleDescription.add("FlyСимулятор голубя");
      this.moduleDescription.add("FakePlayerСпавнит локального бота");
      this.moduleDescription.add("SpiderПозволяет лазить по стенам");
      this.moduleDescription.add("InvWalkХодьба во всех меню");
      this.moduleDescription.add("TimerИзменят субьективную скорость игры");
      this.moduleDescription.add("NameTagsПоказывает информацию об игроке над игроком");
      this.moduleDescription.add("TracersРисует линии к игрокам");
      this.moduleDescription.add("StrafeПозволяет ускорить стрейфинг");
      this.moduleDescription.add("BurrowСтавит блок в ноги");
      this.moduleDescription.add("MiddleClickДрузья/пёрл по колесу мыши");
      this.moduleDescription.add("DashTrailСтремительный след с освещением");
      this.moduleDescription.add("TpDirectionsПоказывает сторону телепортации существ");
      this.moduleDescription.add("MiniMap3d мир на 2d миникарте");
      this.moduleDescription.add("ThrowDirsПеред броском предмета уже будет видно путь его движения");
      this.moduleDescription.add("TPInfluenceЭксплоит увеличенной дистанции указанных действий");
      this.moduleDescription.add("CaveFinderПозволяет видеть сквозь стены полости, шахты, каньёны");
      this.moduleDescription.add("FragEffectsЭпичные эффекты убийств");
      this.moduleDescription.add("CrystalBoosterУскоряет обработку кристалов игрой");
      this.moduleDescription.add("ThrowPetardВы можете кинуть петарду! ОООДАААА");
      this.moduleDescription.add("ThrowFollowАвтоматически швыряет пёрку в догонку за таргетом");
      this.moduleDescription.add("BadTripДобавляет рофельную атмосферу в игру =D");
      this.moduleDescription.add("PenisBuilderПри поставке блока ставится не блок а ЕЛДА БЛЯДЬ =D");
      this.moduleDescription.add("DistantAlphaДелает близкие к камере модели полупрозрачными");
      this.moduleDescription.add("BackTrackПреумножение хитбоксов игроков");
      this.moduleDescription.add("AutoPlayСамостоятельно играет пвп на дуельных режимах");
      this.moduleDescription.add("FriendsSLinkСовместная функция, для обмена координатами и прочим с друзьями");
      this.moduleDescription.add("ObosralipsisИгроки безбожно какаются где хотят, хаос.");
      this.moduleDescription.add("DerpingВизуально сводит с ума вашего персонажа разными способами, видно на сервере.");
      this.moduleDescription.add("WorldChatВизуализирует в 3d над головой игрока сообщение когда он его отправляет в чат.");
      this.moduleDescription.add("RadioPlayerПроигрыватель радио музыки на любой вкус и цвет через интернет, есть виджет в чате.");
      this.moduleDescription
         .add("BedwarsHelperВсячески помогает играть на серверах с режимом Bedwars. (пока-что не работает как должен будет в дальнейших обновлениях) [beta]");
      this.moduleDescription.add("AirStuckОстанавливает ваши движения по всем осям.");
      this.moduleDescription.add("ChestCheckerПоказывает ресурсы сундуков и шалкеров непосредственно на них в 3D без открытия хранилищь вручную.");
      this.moduleDescription
         .add(
            "DualsenseSupportВключает поддержку контроллеров 'Dualsense' и 'Dualsense Edge' для полноценной игры с Vegaline client, имеет некоторые настройки."
         );
      this.moduleDescription.add("PenisУ вас же есть пенис да? Это он.");
      Minecraft.stage("load module descriptions");
      this.modules.sort(Comparator.comparing(module -> -Fonts.comfortaaRegular_18.getStringWidth(module.name)));
      Minecraft.stage("sort modules list");
      safed = new ModuleManager.safe(this.modules);
      Minecraft.stage("save all changes");
   }

   public int getEnabledModulesCount() {
      return (int)this.getModuleList().stream().filter(Module::isActived).count();
   }

   public List<Module> getModuleList() {
      return this.modules;
   }

   public List<String> getModuleDescriptionList() {
      return this.moduleDescription;
   }

   public Module getModule(String name) {
      return this.getModuleList().stream().filter(mod -> mod.getName().equalsIgnoreCase(name)).findAny().orElse(null);
   }

   public static class safe {
      private List<Module> modules = new ArrayList<>();

      public safe(List<Module> modules) {
         this.modules = modules;
      }

      public List<Module> get() {
         return this.modules;
      }
   }
}
